from gtts.tokenizer import pre_processors

import gtts.tokenizer.symbols

class Tokenizer:
  def tokenize(self, input):
    gtts.tokenizer.symbols.SUB_PAIRS.append(('110', 'one one zero'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('210', 'two one zero'))

    gtts.tokenizer.symbols.SUB_PAIRS.append(('0', 'zero'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('9', 'niner'))

    gtts.tokenizer.symbols.SUB_PAIRS.append(('10', 'one zero'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('ten', 'one zero'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('11', 'one one'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('12', 'one two'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('13', 'one three'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('14', 'one four'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('15', 'one five'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('16', 'one six'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('17', 'one seven'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('18', 'one eight'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('19', 'one niner'))

    gtts.tokenizer.symbols.SUB_PAIRS.append(('20', 'two zero'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('twenty', 'two zero'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('21', 'two one'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('22', 'two two'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('23', 'two three'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('24', 'two four'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('25', 'two five'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('26', 'two six'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('27', 'two seven'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('28', 'two eight'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('29', 'two niner'))

    gtts.tokenizer.symbols.SUB_PAIRS.append(('30', 'three zero'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('thirty', 'three zero'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('31', 'three one'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('32', 'three two'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('33', 'three three'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('34', 'three four'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('35', 'three five'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('36', 'three six'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('37', 'three seven'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('38', 'three eight'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('39', 'three niner'))

    gtts.tokenizer.symbols.SUB_PAIRS.append(('40', 'four zero'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('forty', 'four zero'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('41', 'four one'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('42', 'four two'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('43', 'four three'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('44', 'four four'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('45', 'four five'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('46', 'four six'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('47', 'four seven'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('48', 'four eight'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('49', 'four niner'))

    gtts.tokenizer.symbols.SUB_PAIRS.append(('50', 'five zero'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('fifty', 'five zero'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('51', 'five one'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('52', 'five two'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('53', 'five three'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('54', 'five four'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('55', 'five five'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('56', 'five six'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('57', 'five seven'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('58', 'five eight'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('59', 'five niner'))

    gtts.tokenizer.symbols.SUB_PAIRS.append(('60', 'six zero'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('sixty', 'six zero'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('61', 'six one'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('62', 'six two'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('63', 'six three'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('64', 'six four'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('65', 'six five'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('66', 'six six'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('67', 'six seven'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('68', 'six eight'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('69', 'six niner'))

    gtts.tokenizer.symbols.SUB_PAIRS.append(('70', 'seven zero'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('seventy', 'seven zero'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('71', 'seven one'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('72', 'seven two'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('73', 'seven three'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('74', 'seven four'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('75', 'seven five'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('76', 'seven six'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('77', 'seven seven'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('78', 'seven eight'))
    gtts.tokenizer.symbols.SUB_PAIRS.append(('79', 'seven niner'))

    gtts.tokenizer.symbols.SUB_PAIRS.append(('one hundred', '1'))

    return pre_processors.word_sub(input)
